import { NextResponse } from "next/server";
import { Octokit } from "@octokit/rest";
import { generateClaudeMd } from "@/lib/documentGeneration";

export async function POST(request: Request) {
  try {
    const { companyName, documents } = await request.json();

    if (!companyName || !documents?.problemDefinition || !documents?.solutionOnePager || !documents?.developmentPlan) {
      return NextResponse.json(
        { error: "companyName and all three documents are required" },
        { status: 400 }
      );
    }

    const token = process.env.GITHUB_TOKEN;
    const org = process.env.GITHUB_ORG;
    if (!token || !org) {
      return NextResponse.json(
        { error: "GitHub configuration is missing" },
        { status: 500 }
      );
    }

    const octokit = new Octokit({ auth: token });

    // Slugify company name for repo
    const repoName = companyName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");

    // Generate CLAUDE.md from the three documents
    const claudeMdContent = await generateClaudeMd(
      documents.problemDefinition,
      documents.solutionOnePager,
      documents.developmentPlan
    );

    // Create private repo
    let repoUrl: string;
    try {
      const { data: repo } = await octokit.repos.createInOrg({
        org,
        name: repoName,
        private: true,
        description: `Client project for ${companyName}`,
        auto_init: true,
      });
      repoUrl = repo.html_url;
    } catch (err: unknown) {
      const octoErr = err as { status?: number; message?: string };
      if (octoErr.status === 422) {
        return NextResponse.json(
          { error: `Repository "${org}/${repoName}" already exists. Choose a different name or delete the existing repo.` },
          { status: 409 }
        );
      }
      throw err;
    }

    // Commit all files in a single commit using Git Data API
    const { data: ref } = await octokit.git.getRef({
      owner: org,
      repo: repoName,
      ref: "heads/main",
    });
    const baseSha = ref.object.sha;

    const files = [
      { path: "docs/problem-definition.md", content: documents.problemDefinition },
      { path: "docs/solution-one-pager.md", content: documents.solutionOnePager },
      { path: "docs/development-plan.md", content: documents.developmentPlan },
      { path: "CLAUDE.md", content: claudeMdContent },
    ];

    const blobs = await Promise.all(
      files.map((f) =>
        octokit.git.createBlob({
          owner: org,
          repo: repoName,
          content: f.content,
          encoding: "utf-8",
        })
      )
    );

    const { data: tree } = await octokit.git.createTree({
      owner: org,
      repo: repoName,
      base_tree: baseSha,
      tree: files.map((f, i) => ({
        path: f.path,
        mode: "100644" as const,
        type: "blob" as const,
        sha: blobs[i].data.sha,
      })),
    });

    const { data: commit } = await octokit.git.createCommit({
      owner: org,
      repo: repoName,
      message: "Add project documents and CLAUDE.md\n\nGenerated by CrumbLabz CRM",
      tree: tree.sha,
      parents: [baseSha],
    });

    await octokit.git.updateRef({
      owner: org,
      repo: repoName,
      ref: "heads/main",
      sha: commit.sha,
    });

    return NextResponse.json({ repoUrl, repoName });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("Project creation error:", message);
    return NextResponse.json(
      { error: "Failed to create project" },
      { status: 500 }
    );
  }
}
